/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.InlineResponseDefault;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import javax.validation.constraints.*;

@Api(value = "user", description = "the user API")
public interface UserApi {

    @ApiOperation(value = "get a user", notes = "", response = Object.class, tags={ "User", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "a user's base infomation", response = Object.class),
        @ApiResponse(code = 200, message = "unexpected error", response = InlineResponseDefault.class) })
    
    @RequestMapping(value = "/user",
        method = RequestMethod.GET)
    ResponseEntity<Object> userGet( @NotNull@ApiParam(value = "a user's name", required = true) @RequestParam(value = "username", required = true) String username);

}
